[package]
name = "barracuda-driver-ov2640"
version = "0.1.0"
edition = "2024"
description = "Low-level OV2640 image-sensor driver"
license = "Apache-2.0"

[dependencies]
embedded-hal.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
