[package]
name = "barracuda-imessage-qq-plugin"
version = "0.1.0"
edition = "2021"
description = "IMessage QQ provider Plugin"

[build-dependencies]
barracuda-plugin-build = { path = "../../../../core/plugin/crates/build" }

[dependencies]
barracuda-captive-portal-plugin.workspace = true
barracuda-imessage-gateway-channel = { path = "../../../imessage-gateway/crates/channel" }
barracuda-imessage-gateway-plugin.workspace = true
barracuda-plugin.workspace = true
barracuda-webserver-plugin.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
embedded-io-async = "0.7"
http-client.workspace = true
log = "0.4"
qq = { path = "../provider" }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
ws-client.workspace = true

[dev-dependencies]
barracuda-platform.workspace = true
barracuda-platform-test.workspace = true
barracuda-vfs.workspace = true
barracuda-workflow-plugin.workspace = true
embassy-executor = { workspace = true, features = ["platform-std", "executor-thread"] }
embassy-time = { workspace = true, features = ["std", "generic-queue-64"] }
futures-lite = "2"
serde_json = "1"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
