[package]
name = "barracuda-imessage-qq-plugin"
version = "0.1.0"
edition = "2021"
description = "IMessage QQ provider Plugin"

[dependencies]
barracuda-imessage-gateway-plugin.workspace = true
barracuda-plugin.workspace = true
barracuda-webserver-plugin.workspace = true
http-client.workspace = true
log = "0.4"
qq = { path = "../provider" }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
