[package]
name = "barracuda-driver-rx8130ce"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
embedded-hal.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"

[dev-dependencies]
barracuda-platform-virtual-io.workspace = true
