[package]
name = "barracuda-driver-gt911"
version = "0.1.0"
edition = "2024"
description = "Low-level Goodix GT911 touch-controller driver"
license = "Apache-2.0"

[dependencies]
embedded-hal.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
arithmetic_side_effects = "deny"
