[package]
name = "barracuda-board-selected"
version = "0.1.0"
edition = "2021"
description = "Compile-time selected Barracuda Board HAL"

[dependencies]
barracuda-board.workspace = true
barracuda-board-hal.workspace = true
# BEGIN GENERATED SELECTED BOARD HAL

# END GENERATED SELECTED BOARD HAL
embassy-executor.workspace = true

[build-dependencies]
barracuda-board-config.workspace = true
barracuda-board-tool.workspace = true
barracuda-driver-config.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
