[package]
name = "barracuda-mipi-dbi-display"
version = "0.1.0"
edition = "2024"
description = "Barracuda display Driver for MIPI DBI/DCS panels supported by mipidsi"
license = "Apache-2.0"

[dependencies]
barracuda-driver.workspace = true
embedded-graphics-core.workspace = true
embedded-hal.workspace = true
mipidsi.workspace = true
static_cell.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
