idf_component_register(
    SRCS
        "src/display_color.c"
        "src/display_dirty.c"
        "src/display_hal.c"
        "src/display_text.c"
        "src/lua_module_display.c"
    INCLUDE_DIRS
        "src"
    REQUIRES
        lua_runtime
        display_arbiter
        esp_lcd
        esp_painter
        module_image
)
