//! Trust decisions against the compact root bundle.
//!
//! mbedTLS gets an empty CA chain, so the top certificate of every server
//! chain reaches [`verify`] flagged not trusted. The callback looks up that
//! certificate's issuer in the bundle and, when a root of that name signed it,
//! clears the flag; mbedTLS checks the rest of the chain itself. A top
//! certificate that is itself a bundled root (the same name and key) is
//! trusted whoever signed it, since servers send roots cross-signed by older
//! roots the bundle no longer has.
//!
//! Some servers also send that older root, so the top of the path is a root
//! the bundle dropped while a bundled root sits just below it. mbedTLS calls
//! the callback from the top of the verified path down to the server's own
//! certificate, so an untrusted top is set aside in the session's
//! [`VerifyScratch`] rather than rejected: a bundled root met further down the
//! same path settles it, as a browser stops at the first root it trusts, and
//! otherwise the server's certificate is marked not trusted. Only certificates
//! on the path mbedTLS verified reach the callback, so a bundled root the
//! server sends beside an unrelated chain vouches for nothing. Roots stay in
//! flash and only the matching root's key is parsed, during the handshake.
#![allow(unsafe_code)]

use core::ffi::{c_int, c_void};

use mbedtls_rs::sys::{
    mbedtls_md, mbedtls_md_get_size, mbedtls_md_info_from_type, mbedtls_pk_can_do,
    mbedtls_pk_context, mbedtls_pk_free, mbedtls_pk_init, mbedtls_pk_parse_public_key,
    mbedtls_pk_verify_ext, mbedtls_x509_buf, mbedtls_x509_crt, MBEDTLS_ERR_X509_BAD_INPUT_DATA,
    MBEDTLS_X509_BADCERT_BAD_MD, MBEDTLS_X509_BADCERT_NOT_TRUSTED,
};
use mbedtls_rs::VerifyScratch;

/// Generated by `build.rs` from `roots/cacert.pem`; its layout is described there.
static BUNDLE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/roots.bin"));

/// The largest digest mbedTLS produces (`MBEDTLS_MD_MAX_SIZE`).
const MAX_DIGEST: usize = 64;

/// One root of the bundle: its subject name and public key, both DER.
#[derive(Clone, Copy)]
pub(crate) struct Root {
    pub(crate) name: &'static [u8],
    pub(crate) key: &'static [u8],
}

/// Every root in the bundle, in name order.
pub(crate) fn roots() -> impl Iterator<Item = Root> {
    let mut rest = BUNDLE.get(2..).unwrap_or_default();
    core::iter::from_fn(move || {
        let (name_len, key_len) = (read_u16(rest, 0)?, read_u16(rest, 2)?);
        let name = rest.get(4..4 + name_len)?;
        let key = rest.get(4 + name_len..4 + name_len + key_len)?;
        rest = rest.get(4 + name_len + key_len..)?;
        Some(Root { name, key })
    })
}

/// The number of roots the bundle declares.
pub(crate) fn count() -> usize {
    read_u16(BUNDLE, 0).unwrap_or(0)
}

fn read_u16(bytes: &[u8], at: usize) -> Option<usize> {
    let pair = bytes.get(at..at + 2)?;
    Some(usize::from(u16::from_le_bytes([pair[0], pair[1]])))
}

/// The verify callback mbedTLS calls for each certificate of a server chain.
///
/// # Safety
///
/// mbedTLS passes a live certificate and flags, or null, and as context the
/// session's [`VerifyScratch`] or null.
pub(crate) unsafe extern "C" fn verify(
    context: *mut c_void,
    certificate: *mut mbedtls_x509_crt,
    depth: c_int,
    flags: *mut u32,
) -> c_int {
    // SAFETY: the session owns its scratch for as long as its configuration.
    let scratch = unsafe { context.cast::<VerifyScratch>().as_ref() };
    // SAFETY: mbedTLS passes pointers that are valid for this call, or null.
    let (Some(certificate), Some(flags)) =
        (unsafe { certificate.as_ref() }, unsafe { flags.as_mut() })
    else {
        if let Some(scratch) = scratch {
            scratch.0.set(SETTLED);
        }
        return MBEDTLS_ERR_X509_BAD_INPUT_DATA;
    };
    // SAFETY: the buffers belong to the parsed certificate.
    let (issuer, subject, key) = unsafe {
        (
            bytes(&certificate.issuer_raw),
            bytes(&certificate.subject_raw),
            bytes(&certificate.pk_raw),
        )
    };
    let bundled = roots().any(|root| root.name == subject && root.key == key);
    let pending = scratch.is_some_and(|scratch| scratch.0.get() == PENDING);
    if pending && bundled && depth > 0 {
        // The path reaches a bundled root below the untrusted top: whatever
        // the server sent above it, and the digest that signed this copy,
        // does not matter.
        *flags &= !(MBEDTLS_X509_BADCERT_NOT_TRUSTED | MBEDTLS_X509_BADCERT_BAD_MD);
        if let Some(scratch) = scratch {
            scratch.0.set(SETTLED);
        }
    } else if only_untrusted(*flags) {
        judge(certificate, issuer, bundled, depth, flags, scratch);
    }
    if depth == 0 {
        if let Some(scratch) = scratch {
            if scratch.0.replace(SETTLED) == PENDING {
                *flags |= MBEDTLS_X509_BADCERT_NOT_TRUSTED;
            }
        }
    }
    0
}

/// [`VerifyScratch`]: no certificate is waiting for a bundled root below it.
const SETTLED: c_int = 0;
/// [`VerifyScratch`]: a certificate above was set aside; the path must reach a
/// bundled root before the server's own certificate.
const PENDING: c_int = 1;

/// Whether "no trusted parent" is the certificate's sole complaint. A weak
/// digest on its own signature is judged with it; anything else (a name
/// mismatch, a bad intermediate, an expired certificate) stands.
fn only_untrusted(flags: u32) -> bool {
    flags & !MBEDTLS_X509_BADCERT_BAD_MD == MBEDTLS_X509_BADCERT_NOT_TRUSTED
}

/// Trusts `certificate`, flagged only not trusted, when it is a bundled root
/// or a bundled root signed it, or sets it aside for a bundled root below.
fn judge(
    certificate: &mbedtls_x509_crt,
    issuer: &[u8],
    bundled: bool,
    depth: c_int,
    flags: &mut u32,
    scratch: Option<&VerifyScratch>,
) {
    // The server sent a bundled root itself, self-signed or cross-signed by a
    // root the bundle no longer has. A root is trusted as its name and key,
    // so who signed this copy, and with which digest, does not matter.
    if bundled {
        *flags &= !(MBEDTLS_X509_BADCERT_NOT_TRUSTED | MBEDTLS_X509_BADCERT_BAD_MD);
        return;
    }
    for root in roots().filter(|root| root.name == issuer) {
        // SAFETY: the certificate is parsed.
        if unsafe { signed_by(certificate, root.key) } {
            *flags &= !MBEDTLS_X509_BADCERT_NOT_TRUSTED;
            return;
        }
    }
    // Set aside, unless nothing lies below to settle it.
    if let Some(scratch) = scratch.filter(|_| depth > 0) {
        *flags &= !(MBEDTLS_X509_BADCERT_NOT_TRUSTED | MBEDTLS_X509_BADCERT_BAD_MD);
        scratch.0.set(PENDING);
    }
}

/// Whether `key` (a DER SubjectPublicKeyInfo) verifies `certificate`'s signature.
///
/// # Safety
///
/// `certificate` must be a parsed certificate.
unsafe fn signed_by(certificate: &mbedtls_x509_crt, key: &[u8]) -> bool {
    let mut public_key = core::mem::MaybeUninit::<mbedtls_pk_context>::uninit();
    // SAFETY: `mbedtls_pk_init` initializes the whole context, which is freed
    // below on every path.
    unsafe {
        mbedtls_pk_init(public_key.as_mut_ptr());
        let public_key = public_key.assume_init_mut();
        let verified = check(certificate, key, public_key);
        mbedtls_pk_free(public_key);
        verified
    }
}

/// # Safety
///
/// `certificate` must be parsed and `public_key` initialized.
unsafe fn check(
    certificate: &mbedtls_x509_crt,
    key: &[u8],
    public_key: &mut mbedtls_pk_context,
) -> bool {
    // SAFETY: every pointer refers to a live buffer of the stated length.
    unsafe {
        if mbedtls_pk_parse_public_key(public_key, key.as_ptr(), key.len()) != 0
            || mbedtls_pk_can_do(public_key, certificate.private_sig_pk) == 0
        {
            return false;
        }
        let digest_info = mbedtls_md_info_from_type(certificate.private_sig_md);
        if digest_info.is_null() {
            return false;
        }
        let mut digest = [0; MAX_DIGEST];
        let signed = bytes(&certificate.tbs);
        if mbedtls_md(
            digest_info,
            signed.as_ptr(),
            signed.len(),
            digest.as_mut_ptr(),
        ) != 0
        {
            return false;
        }
        let signature = bytes(&certificate.private_sig);
        mbedtls_pk_verify_ext(
            certificate.private_sig_pk,
            certificate.private_sig_opts,
            public_key,
            certificate.private_sig_md,
            digest.as_ptr(),
            usize::from(mbedtls_md_get_size(digest_info)),
            signature.as_ptr(),
            signature.len(),
        ) == 0
    }
}

/// # Safety
///
/// `buffer` must describe `len` readable bytes, or be null.
unsafe fn bytes(buffer: &mbedtls_x509_buf) -> &[u8] {
    if buffer.p.is_null() {
        return &[];
    }
    // SAFETY: guaranteed by the caller.
    unsafe { core::slice::from_raw_parts(buffer.p, buffer.len) }
}
