[package]
name = "barracuda-imessage-bluebubble-plugin"
version = "0.1.0"
edition = "2021"
description = "IMessage BlueBubbles provider Plugin"

[dependencies]
bluebubbles.workspace = true
barracuda-imessage-gateway-plugin.workspace = true
barracuda-plugin-api.workspace = true
barracuda-plugin-manager.workspace = true
barracuda-webserver-plugin.workspace = true
gateway.workspace = true
http-client.workspace = true
log = "0.4"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
