[package]
name = "barracuda-ov3660-camera"
version = "0.1.0"
edition = "2024"
description = "OV3660 QVGA JPEG Camera Driver over embedded-hal control bindings"
license = "Apache-2.0"

[dependencies]
barracuda-driver.workspace = true
embedded-hal.workspace = true

[dev-dependencies]
embassy-futures.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
