[package]
name = "barracuda-ina226-power-monitor"
version = "0.1.0"
edition = "2024"
description = "INA226 voltage and current monitor implementation over embedded-hal I2C"
license = "Apache-2.0"

[dependencies]
barracuda-driver-ina226.workspace = true
barracuda-peripheral.workspace = true
embedded-hal.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
arithmetic_side_effects = "deny"
