[package]
name = "barracuda-workflow-runtime"
version = "0.1.0"
edition = "2021"
publish = false
description = "Direct-action Workflow runtime for Barracuda"

[lib]
crate-type = ["rlib"]

[dependencies]
getset = "0.1.7"
log.workspace = true
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
futures-lite = "2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
arithmetic_side_effects = "deny"
