[package]
name = "barracuda-es8388-es7210-audio-codec"
version = "0.1.0"
edition = "2024"
description = "ES8388 output and ES7210 microphone audio-codec implementation"
license = "Apache-2.0"

[dependencies]
barracuda-driver-es7210.workspace = true
barracuda-driver-es8388.workspace = true
barracuda-driver-pi4ioe5v6408.workspace = true
barracuda-peripheral.workspace = true
embedded-hal.workspace = true

[dev-dependencies]
embassy-futures.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
