[package]
name = "barracuda-rx8130ce-rtc"
version = "0.1.0"
edition = "2024"
description = "RX8130CE real-time clock implementation over embedded-hal I2C"
license = "Apache-2.0"

[dependencies]
barracuda-driver-rx8130ce.workspace = true
barracuda-peripheral.workspace = true
embedded-hal.workspace = true

[dev-dependencies]
embassy-futures.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
arithmetic_side_effects = "deny"
