[package]
name = "barracuda-apa102-led-strip"
version = "0.1.0"
edition = "2024"
description = "APA102 and SK9822 LED-strip implementation over embedded-hal SPI"
license = "Apache-2.0"

[dependencies]
portable-atomic.workspace = true
barracuda-driver-apa102.workspace = true
barracuda-peripheral.workspace = true
embedded-hal.workspace = true

[dev-dependencies]
embassy-futures.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
