[package]
name = "barracuda-message-queue-plugin"
version = "0.1.0"
edition = "2024"
description = "Barracuda Plugin providing shared bounded queues to Lua"
license = "Apache-2.0"

[dependencies]
portable-atomic-util.workspace = true
portable-atomic.workspace = true
barracuda-plugin.workspace = true
barracuda-vm-plugin.workspace = true
embassy-sync.workspace = true
futures-util = { workspace = true, features = ["alloc", "async-await"] }
spin = { version = "0.10", default-features = false, features = ["portable_atomic", "mutex", "spin_mutex"] }

[dev-dependencies]
critical-section = { version = "1", features = ["std"] }
futures-lite = "2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
