[package]
name = "barracuda-plugin-api"
version = "0.1.0"
edition = "2021"
publish = false
description = "Construction context shared by Barracuda Plugins"

[lib]
crate-type = ["rlib"]

[dependencies]
portable-atomic-util.workspace = true
barracuda-board-hal.workspace = true
barracuda-target-api.workspace = true
embassy-net.workspace = true
http-client.workspace = true

[dev-dependencies]
barracuda-platform-test.workspace = true
embassy-time = { workspace = true, features = ["std", "generic-queue-64"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
