[package]
name = "barracuda-gdeh0154d67-display"
version = "0.1.0"
edition = "2024"
description = "Buffered GDEH0154D67 e-paper Driver for Barracuda"
license = "Apache-2.0"

[dependencies]
barracuda-driver.workspace = true
embedded-graphics-core.workspace = true
embedded-hal.workspace = true
epd-waveshare.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
