name: m5stack-stick-s3
hardware:
  chip: esp32s3
toolchain:
  target: xtensa-esp32s3-none-elf
native-layout:
  artifact: partitions.csv
peripherals:
  io:
    spi-device:
      display-spi:
        peripheral: SPI3
        sck: GPIO40
        mosi: GPIO39
        chip-select: GPIO41
        frequency-hz: 40000000
  devices:
    display:
      implementation: mipi-dbi-display
      bindings: { backlight: GPIO38, dc: GPIO45, reset: GPIO21, spi: display-spi }
      parameters:
        controller: st7789
        width: 135
        height: 240
        offset-x: 52
        offset-y: 40
        invert-colors: true
