name: m5stack-din-meter
hardware:
  chip: esp32s3
toolchain:
  target: xtensa-esp32s3-none-elf
native-layout:
  artifact: partitions.csv
internal-io:
  spi-device:
    display-spi:
      peripheral: SPI2
      sck: GPIO6
      mosi: GPIO5
      chip-select: GPIO7
      frequency-hz: 40000000
builtin-peripherals:
  display:
    driver: mipi-dbi-display
    bindings: { backlight: GPIO9, dc: GPIO4, reset: GPIO8, spi: display-spi }
    parameters:
      controller: st7789
      width: 135
      height: 240
      offset-x: 52
      offset-y: 40
      invert-colors: true
