[package]
name = "barracuda-driver"
version = "0.1.0"
edition = "2024"
description = "Stable Driver and built-in peripheral capability APIs for Barracuda"
license = "Apache-2.0"

[dependencies]
embedded-graphics-core.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
