[package]
name = "barracuda-plugin-manager"
authors = ["Finn(Ziheng) Sheng <zsheng2@ncsu.edu>"]
version = "0.1.0"
edition = "2021"
publish = false
description = "Plugin management and scoped persistent storage for Barracuda"
readme = "README.md"

[lib]
crate-type = ["rlib"]

[dependencies]
portable-atomic-util.workspace = true
barracuda-kv.workspace = true
barracuda-vfs.workspace = true
embassy-executor.workspace = true
embassy-sync.workspace = true
embedded-storage-async.workspace = true
getset = "0.1.7"
log.workspace = true
thiserror = { version = "2", default-features = false }

[dev-dependencies]
barracuda-platform-test.workspace = true
barracuda-vfs-memfs.workspace = true
futures-lite = "2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
arithmetic_side_effects = "deny"
