//! STM32 process entry and bootstrap resources.

use core::cell::RefCell;

use barracuda_platform::UnavailableNetworkDriver;
use embassy_net::{Runner, StackResources};
use embassy_stm32::flash::Flash;
use embassy_sync::blocking_mutex::{raw::CriticalSectionRawMutex, Mutex};
use panic_halt as _;
use static_cell::StaticCell;

use crate::{Stm32Flash, Stm32PlatformBindings, Stm32PlatformError};

#[doc(hidden)]
pub use cortex_m_rt as __rt;
#[doc(hidden)]
pub use embassy_stm32 as __hal;
#[doc(hidden)]
pub use log as __log;
#[doc(hidden)]
pub use static_cell::StaticCell as __StaticCell;

/// Bytes of internal RAM given to the global allocator.
const HEAP_SIZE: usize = 96 * 1024;

#[global_allocator]
static HEAP: embedded_alloc::TlsfHeap = embedded_alloc::TlsfHeap::empty();

embassy_stm32::bind_interrupts!(struct Irqs {
    FLASH => embassy_stm32::flash::InterruptHandler;
});

#[embassy_executor::task]
async fn run_network(mut runner: Runner<'static, UnavailableNetworkDriver>) -> ! {
    runner.run().await
}

/// Installs a static internal-RAM region as the global heap.
#[doc(hidden)]
pub fn initialize_allocator() {
    // SAFETY: the entry calls this once, before anything allocates.
    #[allow(unsafe_code)]
    unsafe {
        embedded_alloc::init!(HEAP, HEAP_SIZE);
    }
}

/// Creates the process-lifetime mechanisms needed by the selected STM32 Platform.
pub fn bindings(
    board: &barracuda_board::Board,
    spawner: embassy_executor::Spawner,
    flash_token: embassy_stm32::Peri<'static, embassy_stm32::peripherals::FLASH>,
) -> Result<Stm32PlatformBindings, Stm32PlatformError> {
    static NETWORK: StaticCell<StackResources<4>> = StaticCell::new();
    static FLASH: StaticCell<Mutex<CriticalSectionRawMutex, RefCell<Stm32Flash>>> =
        StaticCell::new();

    // The Board's Ethernet is not wired into the Platform yet, so the IP
    // stack never has a link.
    let (ip_stack, runner) = embassy_net::new(
        UnavailableNetworkDriver,
        embassy_net::Config::default(),
        NETWORK.init(StackResources::new()),
        0,
    );
    let network = run_network(runner).map_err(|_error| Stm32PlatformError::NetworkTask)?;
    spawner.spawn(network);
    let flash = FLASH.init(Mutex::new(RefCell::new(Flash::new(flash_token, Irqs))));
    Stm32PlatformBindings::from_initialized_services(board, ip_stack, flash)
}

/// Generates the STM32 async entry around one selected application.
#[macro_export]
macro_rules! platform_entry {
    ($board:expr, $board_bindings:ident, $board_bindings_type:path, |$spawner:ident, $platform_bindings:ident, $board_bindings_value:ident| $application:expr) => {
        #[embassy_executor::task]
        async fn __barracuda_application_task(
            $spawner: embassy_executor::Spawner,
            $board_bindings_value: $board_bindings_type,
            flash: $crate::application::__hal::Peri<
                'static,
                $crate::application::__hal::peripherals::FLASH,
            >,
        ) {
            let $platform_bindings = match $crate::application::bindings($board, $spawner, flash) {
                Ok(bindings) => bindings,
                Err(error) => {
                    $crate::application::__log::error!(
                        "failed to bootstrap STM32 Platform: {}",
                        error
                    );
                    loop {
                        core::hint::spin_loop();
                    }
                }
            };
            if let Err(error) = $application.await {
                $crate::application::__log::error!("application exited: {}", error);
                loop {
                    core::hint::spin_loop();
                }
            }
        }

        #[doc = "STM32 firmware entry point generated by the selected Platform."]
        #[$crate::application::__rt::entry]
        fn main() -> ! {
            $crate::application::initialize_allocator();
            let peripherals =
                $crate::application::__hal::init($crate::application::__hal::Config::default());
            let $board_bindings_value = $board_bindings!(peripherals);
            let flash = peripherals.FLASH;
            static EXECUTOR: $crate::application::__StaticCell<embassy_executor::Executor> =
                $crate::application::__StaticCell::new();
            EXECUTOR
                .init(embassy_executor::Executor::new())
                .run(move |spawner| {
                    if let Ok(task) =
                        __barracuda_application_task(spawner, $board_bindings_value, flash)
                    {
                        spawner.spawn(task);
                    }
                })
        }
    };
}
