[package]
name = "barracuda-imessage-web-plugin"
version = "0.1.0"
edition = "2021"
description = "IMessage Web provider Plugin"

[dependencies]
barracuda-imessage-gateway-plugin.workspace = true
barracuda-plugin.workspace = true
barracuda-webserver-plugin.workspace = true
log.workspace = true
web = { path = "../provider", features = ["server"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
