[package]
name = "barracuda-http-plugin"
version = "0.1.0"
edition = "2024"
description = "Outbound HTTP JSON RPC Plugin for Barracuda"
license = "Apache-2.0"

[dependencies]
barracuda-event-router.workspace = true
barracuda-plugin.workspace = true
embedded-io = "0.7"
embedded-io-async = "0.7"
http-client.workspace = true
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc", "raw_value"] }

[dev-dependencies]
barracuda-platform-test.workspace = true
embassy-time = { workspace = true, features = ["std", "generic-queue-64"] }
futures-lite = "2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
