include = [{ path = "../.barracuda/cargo.toml", optional = true }]

[alias]
board = ["run", "--config", "unstable.build-std=[\"std\"]", "--target-dir", "target/host-tools", "--target", "host-tuple", "--quiet", "--package", "barracuda-board-tool", "--"]
cli = ["run", "--config", "unstable.build-std=[\"std\"]", "--target-dir", "target/host-tools", "--target", "host-tuple", "--package", "barracuda-cli", "--"]
platform = ["run", "--config", "unstable.build-std=[\"std\"]", "--target-dir", "target/host-tools", "--target", "host-tuple", "--quiet", "--package", "barracuda-platform-tool", "--"]
plugin = ["run", "--config", "unstable.build-std=[\"std\"]", "--target-dir", "target/host-tools", "--target", "host-tuple", "--quiet", "--package", "barracuda-plugin-tool", "--"]
image = ["run", "--config", "unstable.build-std=[\"std\"]", "--target-dir", "target/host-tools", "--target", "host-tuple", "--quiet", "--package", "barracuda-system-image", "--"]
