[package]
name = "barracuda-indicator-led"
version = "0.1.0"
edition = "2024"
description = "Reusable indicator LED implementation over embedded-hal"
license = "Apache-2.0"

[dependencies]
barracuda-peripheral.workspace = true
embedded-hal.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
