[package]
name = "barracuda-vfs-littlefs"
version = "0.1.0"
edition = "2021"
description = "LittleFS backend for the Barracuda VFS"

[lib]
crate-type = ["rlib"]

[dependencies]
barracuda-vfs.workspace = true
embedded-io-async = "0.7"
embedded-storage = "0.3"
generic-array = "0.14"
spin = { version = "0.10", default-features = false, features = ["mutex", "spin_mutex"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
littlefs2 = { version = "0.8", default-features = false, features = ["alloc"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
littlefs2 = { version = "0.8", default-features = false, features = ["alloc", "c-stubs"] }

[dev-dependencies]
critical-section = { version = "1", features = ["std"] }
embassy-futures = { workspace = true }
typenum = "1"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
