[package]
name = "barracuda-lua"
version = "0.1.0"
edition = "2024"
publish = false
description = "Minimal no_std Lua wrapper with native Rust async bindings"
license = "Apache-2.0"

[features]
default = []
vendored = ["dep:cc", "dep:libm"]

[dependencies]
barracuda-bulk-memory.workspace = true
getset = "0.1.7"
libm = { version = "0.2", optional = true }

[build-dependencies]
cc = { version = "1", optional = true }

[dev-dependencies]
portable-atomic.workspace = true
async-channel.workspace = true
futures-lite = "2"
