[package]
name = "barracuda-lua"
version = "0.1.0"
edition = "2024"
description = "Minimal no_std Lua wrapper with native Rust async bindings"
license = "Apache-2.0"

[features]
default = []
vendored = ["lunka/link-vendored"]

[dependencies]
async-channel = { version = "2.5", default-features = false }
getset = "0.1.7"
lunka = { path = "../../../../shared/lunka", default-features = false, features = ["alloc", "auxlib", "stdlibs"] }

[dev-dependencies]
futures-lite = "2"
