name: stm32f429zi-nucleo
hardware:
  chip: stm32f429zi
toolchain:
  target: thumbv7em-none-eabihf
native-layout:
  artifact: memory.x
peripherals:
  devices:
    status-led:
      implementation: indicator-led
      bindings:
        # NUCLEO-F429ZI UM1974 default SB120/SB127 routing: green LD1 is PB0.
        pin: PB0
      parameters:
        active-level: high
exposed-io:
  pins:
    user-button:
      # UM1974: blue B1 user button is connected to PC13.
      pin: PC13
