MEMORY
{
  FLASH       : ORIGIN = 0x08000000, LENGTH = 512K
  DFU         : ORIGIN = 0x08080000, LENGTH = 512K
  BOOT_STATE  : ORIGIN = 0x08100000, LENGTH = 128K
  FILESYSTEM  : ORIGIN = 0x08120000, LENGTH = 256K
  WEB_ASSETS  : ORIGIN = 0x08160000, LENGTH = 256K
  DATABASE    : ORIGIN = 0x081A0000, LENGTH = 384K
  RAM         : ORIGIN = 0x20000000, LENGTH = 128K
}

__active_start = ORIGIN(FLASH);
__active_end = ORIGIN(FLASH) + LENGTH(FLASH);
__dfu_start = ORIGIN(DFU);
__dfu_end = ORIGIN(DFU) + LENGTH(DFU);
__bootloader_state_start = ORIGIN(BOOT_STATE);
__bootloader_state_end = ORIGIN(BOOT_STATE) + LENGTH(BOOT_STATE);
__filesystem_start = ORIGIN(FILESYSTEM);
__filesystem_end = ORIGIN(FILESYSTEM) + LENGTH(FILESYSTEM);
__web_assets_start = ORIGIN(WEB_ASSETS);
__web_assets_end = ORIGIN(WEB_ASSETS) + LENGTH(WEB_ASSETS);
__database_start = ORIGIN(DATABASE);
__database_end = ORIGIN(DATABASE) + LENGTH(DATABASE);
