[package]
name = "barracuda-time-plugin"
version = "0.1.0"
edition = "2024"
description = "Barracuda Plugin that publishes a network-synchronized UTC clock"
license = "Apache-2.0"

[dependencies]
barracuda-plugin.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-net.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
getset = "0.1"
log.workspace = true
sntpc = { version = "0.11.0", default-features = false }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
barracuda-platform-test.workspace = true
embassy-executor = { workspace = true, features = ["arch-std", "executor-thread"] }
embassy-time = { workspace = true, features = ["std", "generic-queue-64"] }
futures-lite = "2"
static_cell = "2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
