//! Render parsed manifests into Rust source: a single `ENTRIES` array of typed
//! `AgentCatalogEntry` values. The output is `include!`-d into
//! `crate::agent_catalog`.
//!
//! Generation uses `quote` to build a typed `proc_macro2::TokenStream` rather
//! than hand-concatenating source strings, so string escaping, slice literals,
//! and integer suffixes are handled for us and the fragments are syntactically
//! checked.

use proc_macro2::TokenStream;
use quote::quote;

use crate::parse::ParsedManifest;

/// Render the full generated module body for `kinds` (assumed already sorted for
/// deterministic output): the catalog array and its verified root identity.
pub(crate) fn render(kinds: &[ParsedManifest], root_kind: &str) -> String {
    let entries = kinds.iter().map(render_entry);

    let body = quote! {
        #[doc = "Every firmware-baked agent definition, one entry per kind."]
        const ENTRIES: &[AgentCatalogEntry] = &[
            #(#entries),*
        ];

        #[doc = "The sole firmware-baked root agent kind."]
        static ROOT_KIND: AgentKind = AgentKind::from_static(#root_kind);
    };

    format!(
        "// @generated by claw-core/manifest_gen/ — do not edit by hand.\n\
         // Source: resources/agents/<kind>/ parsed at compile time.\n\n{body}\n"
    )
}

/// One `AgentCatalogEntry { ... }` array entry.
fn render_entry(kind: &ParsedManifest) -> TokenStream {
    let kind_name = &kind.kind;
    let description = &kind.description;
    let spawn_enabled = kind.spawn_enabled;
    let allowed_kinds = kind.allowed_kinds.iter();
    let retries = kind.retries;
    let tool_blacklist = kind.tool_blacklist.iter();
    let instructions = render_instructions(kind);

    quote! {
        AgentCatalogEntry {
            kind: AgentKind::from_static(#kind_name),
            description: #description,
            runtime: AgentRuntimeManifest {
                retries: #retries,
                tool_blacklist: &[#(#tool_blacklist),*],
                instructions: #instructions,
            },
            multiagent: MultiagentManifest {
                spawn_enabled: #spawn_enabled,
                allowed_kinds: &[#(AgentKind::from_static(#allowed_kinds)),*],
            },
        }
    }
}

/// Render the `instructions` field: the shared `common/instructions.md` preamble
/// prepended (with a blank-line separator) to the kind's own `instructions.md`.
///
/// Both files are pulled in with `include_str!` and joined by `concat!` at
/// compile time, so no instruction bytes are duplicated into the generated
/// source. (`AgentConfig::from_manifest` trims the result, so an empty preamble
/// contributes nothing.)
fn render_instructions(kind: &ParsedManifest) -> TokenStream {
    let own = kind
        .instructions_path
        .to_str()
        .expect("instructions.md path is valid UTF-8");
    let preamble = kind
        .common_instructions_path
        .to_str()
        .expect("common/instructions.md path is valid UTF-8");
    quote! { concat!(include_str!(#preamble), "\n\n", include_str!(#own)) }
}
