//! Marks builds whose concrete target dependencies were generated by the build driver.

fn main() {
    println!("cargo:rustc-check-cfg=cfg(barracuda_generated_build)");
    println!("cargo:rerun-if-env-changed=BARRACUDA_GENERATED_BUILD");
    if std::env::var("BARRACUDA_GENERATED_BUILD").as_deref() == Ok("1") {
        println!("cargo:rustc-cfg=barracuda_generated_build");
    }
}
